name: Project CI

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node: ['20']

    name: Node ${{ matrix.node }}

    steps:
      - uses: actions/checkout@v3

      # Setup Node
      - name: Use Node.js ${{ matrix.node }}
        uses: actions/setup-node@v3
        with:
          node-version: '${{ matrix.node }}'
          cache: 'npm'
          cache-dependency-path: frontend/package-lock.json
      - run: npm install --immutable

      - name: Build frontend
        run: npm run build
